In [5]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier,RandomForestClassifier
from sklearn.svm import  SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier 
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,f1_score,classification_report

In [7]:
df = pd.read_csv(r"C:\Users\Ameet Computer\OneDrive\Pictures\Saved Pictures\customer churn analytics\telco_cleaned.csv")
df.head(6)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,TenureGroup,ChargeGroup,CustomerLifetimeValue,ServiceCount,HighRiskCustomer
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,Yes,Electronic check,29.85,29.85,No,0-12,Low,29.85,1,True
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,Mailed check,56.95,1889.50,No,25-36,Medium,1936.30,3,False
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,Yes,Mailed check,53.85,108.15,Yes,0-12,Medium,107.70,3,True
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,No,Bank transfer (automatic),42.30,1840.75,No,37-48,Medium,1903.50,3,False
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,Yes,Electronic check,70.70,151.65,Yes,0-12,High,141.40,1,True
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,Electronic check,99.65,820.50,Yes,0-12,Premium,797.20,4,True

In [8]:
df.dtypes

customerID                object
gender                    object
SeniorCitizen              int64
Partner                   object
Dependents                object
tenure                     int64
PhoneService              object
MultipleLines             object
InternetService           object
OnlineSecurity            object
OnlineBackup              object
DeviceProtection          object
TechSupport               object
StreamingTV               object
StreamingMovies           object
Contract                  object
PaperlessBilling          object
PaymentMethod             object
MonthlyCharges           float64
TotalCharges             float64
Churn                     object
TenureGroup               object
ChargeGroup               object
CustomerLifetimeValue    float64
ServiceCount               int64
HighRiskCustomer            bool
dtype: object

In [9]:
df.isnull().sum()

customerID                0
gender                    0
SeniorCitizen             0
Partner                   0
Dependents                0
tenure                    0
PhoneService              0
MultipleLines             0
InternetService           0
OnlineSecurity            0
OnlineBackup              0
DeviceProtection          0
TechSupport               0
StreamingTV               0
StreamingMovies           0
Contract                  0
PaperlessBilling          0
PaymentMethod             0
MonthlyCharges            0
TotalCharges             11
Churn                     0
TenureGroup              11
ChargeGroup               0
CustomerLifetimeValue     0
ServiceCount              0
HighRiskCustomer          0
dtype: int64

In [10]:
df.dropna(inplace=True)

In [11]:
df.isnull().sum()

customerID               0
gender                   0
SeniorCitizen            0
Partner                  0
Dependents               0
tenure                   0
PhoneService             0
MultipleLines            0
InternetService          0
OnlineSecurity           0
OnlineBackup             0
DeviceProtection         0
TechSupport              0
StreamingTV              0
StreamingMovies          0
Contract                 0
PaperlessBilling         0
PaymentMethod            0
MonthlyCharges           0
TotalCharges             0
Churn                    0
TenureGroup              0
ChargeGroup              0
CustomerLifetimeValue    0
ServiceCount             0
HighRiskCustomer         0
dtype: int64

In [12]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
7038    False
7039    False
7040    False
7041    False
7042    False
Length: 7032, dtype: bool

In [42]:
if "customerID" in df.columns:
    df.drop("customerID", axis=1, inplace=True)

In [14]:
######converting to binary encoder label adn one hot labelencoder 



for col in binary_cols:
    binary_cols = ["gender", "Partner", "Dependents", "PhoneService", "PaperlessBilling", "Churn"]

    for col in binary_cols:
        df[col] = df[col].replace({
            'Yes': 1,
            'No': 0,
            'Male': 1,
            'Female': 0
        })

C:\Users\Ameet Computer\AppData\Local\Temp\ipykernel_16364\1071181523.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].replace({

In [16]:
df = pd.get_dummies(df,drop_first=True)

In [17]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,...,PaymentMethod_Electronic check,PaymentMethod_Mailed check,TenureGroup_13-24,TenureGroup_25-36,TenureGroup_37-48,TenureGroup_49-60,TenureGroup_61-72,ChargeGroup_Low,ChargeGroup_Medium,ChargeGroup_Premium
0,0,0,1,0,1,0,1,29.85,29.85,0,...,True,False,False,False,False,False,False,True,False,False
1,1,0,0,0,34,1,0,56.95,1889.50,0,...,False,True,False,True,False,False,False,False,True,False
2,1,0,0,0,2,1,1,53.85,108.15,1,...,False,True,False,False,False,False,False,False,True,False
3,1,0,0,0,45,0,0,42.30,1840.75,0,...,False,False,False,False,True,False,False,False,True,False
4,0,0,0,0,2,1,1,70.70,151.65,1,...,True,False,False,False,False,False,False,False,False,False

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Columns: 7073 entries, gender to ChargeGroup_Premium
dtypes: bool(7061), float64(3), int64(9)
memory usage: 48.1 MB

In [19]:
df.describe()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,CustomerLifetimeValue,ServiceCount
count,7032.000000,7032.000000,7032.000000,7032.000000,7032.000000,7032.000000,7032.000000,7032.000000,7032.000000,7032.000000,7032.000000,7032.000000
mean,0.504693,0.162400,0.482509,0.298493,32.421786,0.903299,0.592719,64.798208,2283.300441,0.265785,2283.147248,2.941411
std,0.500014,0.368844,0.499729,0.457629,24.545260,0.295571,0.491363,30.085974,2266.771362,0.441782,2264.703327,1.843695
min,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,18.250000,18.800000,0.000000,18.800000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,9.000000,1.000000,0.000000,35.587500,401.450000,0.000000,397.800000,1.000000
50%,1.000000,0.000000,0.000000,0.000000,29.000000,1.000000,1.000000,70.350000,1397.475000,0.000000,1394.575000,3.000000
75%,1.000000,0.000000,1.000000,1.000000,55.000000,1.000000,1.000000,89.862500,3794.737500,1.000000,3791.250000,4.000000
max,1.000000,1.000000,1.000000,1.000000,72.000000,1.000000,1.000000,118.750000,8684.800000,1.000000,8550.000000,7.000000

In [23]:
x = df.drop("Churn", axis=1)
y = df["Churn"]

In [24]:
x

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,CustomerLifetimeValue,...,PaymentMethod_Electronic check,PaymentMethod_Mailed check,TenureGroup_13-24,TenureGroup_25-36,TenureGroup_37-48,TenureGroup_49-60,TenureGroup_61-72,ChargeGroup_Low,ChargeGroup_Medium,ChargeGroup_Premium
0,0,0,1,0,1,0,1,29.85,29.85,29.85,...,True,False,False,False,False,False,False,True,False,False
1,1,0,0,0,34,1,0,56.95,1889.50,1936.30,...,False,True,False,True,False,False,False,False,True,False
2,1,0,0,0,2,1,1,53.85,108.15,107.70,...,False,True,False,False,False,False,False,False,True,False
3,1,0,0,0,45,0,0,42.30,1840.75,1903.50,...,False,False,False,False,True,False,False,False,True,False
4,0,0,0,0,2,1,1,70.70,151.65,141.40,...,True,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,1,84.80,1990.50,2035.20,...,False,True,True,False,False,False,False,False,False,False
7039,0,0,1,1,72,1,1,103.20,7362.90,7430.40,...,False,False,False,False,False,False,True,False,False,True
7040,0,0,1,1,11,0,1,29.60,346.45,325.60,...,True,False,False,False,False,False,False,True,False,False
7041,1,1,1,0,4,1,1,74.40,306.60,297.60,...,False,True,False,False,False,False,False,False,False,False
7042,1,0,0,0,66,1,1,105.65,6844.50,6972.90,...,False,False,False,False,False,False,True,False,False,True

In [25]:
y

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7032, dtype: int64

In [26]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

In [27]:
scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [30]:
model = LogisticRegression(max_iter=1000)
model.fit(x_train,y_train)
y_pred = model.predict(x_test)

print("Logistic Regression")
print("accuracy_score:", accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

C:\Users\Ameet Computer\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Logistic Regression
accuracy_score: 0.7910447761194029
[[933 100]
 [194 180]]
              precision    recall  f1-score   support

           0       0.83      0.90      0.86      1033
           1       0.64      0.48      0.55       374

    accuracy                           0.79      1407
   macro avg       0.74      0.69      0.71      1407
weighted avg       0.78      0.79      0.78      1407

Continues until it finds the best coefficients or reaches the maximum number of iterations (max_iter).

In [31]:
model = RandomForestClassifier(n_estimators=100)
model.fit(x_train,y_train)
y_pred = model.predict(x_test)

print("RandomForestClassifier")
print("accuracy_score:", accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

RandomForestClassifier
accuracy_score: 0.7960199004975125
[[955  78]
 [209 165]]
              precision    recall  f1-score   support

           0       0.82      0.92      0.87      1033
           1       0.68      0.44      0.53       374

    accuracy                           0.80      1407
   macro avg       0.75      0.68      0.70      1407
weighted avg       0.78      0.80      0.78      1407

In [32]:
model = DecisionTreeClassifier()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)

print("DecisionTree Classifier")
print("accuracy_score:", accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

DecisionTree Classifier
accuracy_score: 0.7583511016346838
[[888 145]
 [195 179]]
              precision    recall  f1-score   support

           0       0.82      0.86      0.84      1033
           1       0.55      0.48      0.51       374

    accuracy                           0.76      1407
   macro avg       0.69      0.67      0.68      1407
weighted avg       0.75      0.76      0.75      1407

In [34]:
model = XGBClassifier()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)

print("XGBClassifier")
print("accuracy_score:", accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

XGBClassifier
accuracy_score: 0.7718550106609808
[[901 132]
 [189 185]]
              precision    recall  f1-score   support

           0       0.83      0.87      0.85      1033
           1       0.58      0.49      0.54       374

    accuracy                           0.77      1407
   macro avg       0.71      0.68      0.69      1407
weighted avg       0.76      0.77      0.77      1407

In [35]:
model = GaussianNB()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)

print("Naive_Bayes")
print("accuracy_score:", accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Naive_Bayes
accuracy_score: 0.6368159203980099
[[568 465]
 [ 46 328]]
              precision    recall  f1-score   support

           0       0.93      0.55      0.69      1033
           1       0.41      0.88      0.56       374

    accuracy                           0.64      1407
   macro avg       0.67      0.71      0.63      1407
weighted avg       0.79      0.64      0.66      1407

In [36]:
model = GradientBoostingClassifier()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)

print("GradientBOOST")
print("accuracy_score:", accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

GradientBOOST
accuracy_score: 0.7903340440653873
[[929 104]
 [191 183]]
              precision    recall  f1-score   support

           0       0.83      0.90      0.86      1033
           1       0.64      0.49      0.55       374

    accuracy                           0.79      1407
   macro avg       0.73      0.69      0.71      1407
weighted avg       0.78      0.79      0.78      1407

In [37]:
model = LGBMClassifier()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)

print("lgbmClassifier")
print("accuracy_score:", accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

lgbmClassifier
accuracy_score: 0.7860696517412935
[[918 115]
 [186 188]]
              precision    recall  f1-score   support

           0       0.83      0.89      0.86      1033
           1       0.62      0.50      0.56       374

    accuracy                           0.79      1407
   macro avg       0.73      0.70      0.71      1407
weighted avg       0.78      0.79      0.78      1407

which features are causing churn

In [39]:
importance = model.feature_importances_

feature_importance = pd.DataFrame({
    "Feature": x.columns,
    "Importance": importance
})

feature_importance = feature_importance.sort_values(
    by="Importance",
    ascending=False
)

print(feature_importance.head(10))

                             Feature  Importance
7                     MonthlyCharges         691
8                       TotalCharges         440
9              CustomerLifetimeValue         403
4                             tenure         372
0                             gender          97
7062  PaymentMethod_Electronic check          86
6                   PaperlessBilling          68
7050                OnlineBackup_Yes          66
10                      ServiceCount          64
3                         Dependents          53

In [ ]:
from sklearn.model_selection import StratifiedKFold, cross_val_score

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()

models_to_test = {
    "LogisticRegression": LogisticRegression(max_iter=2000, class_weight='balanced'),
    "RandomForest": RandomForestClassifier(n_estimators=100, class_weight='balanced'),
    "DecisionTree": DecisionTreeClassifier(class_weight='balanced'),
    "XGBoost": XGBClassifier(scale_pos_weight=scale_pos_weight, use_label_encoder=False, eval_metric='logloss'),
    "LightGBM": LGBMClassifier(class_weight='balanced'),
    "GradientBoosting": GradientBoostingClassifier(),
    "NaiveBayes": GaussianNB()
}

for name, m in models_to_test.items():
    scores = cross_val_score(m, x_train_scaled, y_train, cv=cv, scoring='roc_auc')
    print(f"{name}: ROC-AUC = {scores.mean():.4f} (+/- {scores.std():.4f})")

for name, m in models_to_test.items():
    scores = cross_val_score(m, x_train_scaled, y_train, cv=cv, scoring='roc_auc')
    print(f"{name}: ROC-AUC = {scores.mean():.4f} (+/- {scores.std():.4f})")

NameError: name 'scale_pos_weight' is not defined